spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://127.0.0.1/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.28.131
    port: 6379

server:
  context-path: /sell

#logging:
#  pattern:
#    console: "%d - %msg%n"
##  path: /var/log/tomcat/
#  file: /var/log/tomcat/sell.log
#  level:
#    com.imooc.LoggerTest: debug

wechat:
  mpAppId: xxxxxxxxxxxxx
  mpAppSecret: xxxxxxxxxxx
  openAppId: xxxxxxxxxxxx
  openAppSecret: xxxxxxxxxxxxxxxxxx
  mchId: xxxxxxxxxx
  mchKey: xxxxxxxxxxxxxxxxxxxxx
  # 证书路径
  keyPath: xxxxxxxxxxxxxxxxxxx
  # 异步通知地址 ***
  notifyUrl: xxxxxxxxxxxxxxxxxxxxxxxxx
  templateId:
    orderStatus: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

projectUrl:
  wechatMpAuthorize: http://sell.natapp5.cc
  wechatOpenAuthorize: http://sell.natapp5.cc
  sell: http://sell.natapp5.cc
